version: '3.8'

services:
  mcp-filesystem:
    build: .
    volumes:
      - ${PROJECTS_DIR:-./data}:/projects
    environment:
      - NODE_ENV=production
    ports:
      - "3000:3000"
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').request({hostname:'localhost',port:3000,path:'/health',timeout:2000}).end().on('error',()=>process.exit(1))"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s